-- ChittiApp initial schema
-- Replaces Firestore document-per-group with 5 normalized tables.
-- All IDs use the same string UUIDs generated by the mobile app (uuid v4).

-- ─────────────────────────── TABLES ────────────────────────────────────

create table if not exists public.groups (
  id                     text primary key,
  uid                    text not null,
  name                   text not null,
  description            text,
  amount                 integer not null,
  total_members          integer not null,
  duration_months        integer not null,
  draw_type              text not null default 'lottery',
  foreman_commission_pct numeric(5,2) not null default 5,
  max_discount_pct       numeric(5,2) not null default 30,
  start_date             text not null default '',
  start_day              integer not null default 1,
  start_month            integer not null default 0,
  start_year             integer not null default 2024,
  payment_day            integer not null default 1,
  created_at             timestamptz not null default now(),
  is_active              boolean not null default true
);

create table if not exists public.members (
  id             text primary key,
  group_id       text not null references public.groups(id) on delete cascade,
  name           text not null,
  phone          text not null,
  has_received   boolean not null default false,
  cycle_received integer,
  joined_at      text not null default '',
  share_token    text unique
);

create table if not exists public.cycles (
  id                   text primary key,
  group_id             text not null references public.groups(id) on delete cascade,
  cycle_number         integer not null,
  date                 text not null default '',
  winner_id            text references public.members(id),
  win_amount           integer not null default 0,
  discount             integer,
  foreman_commission   integer,
  dividend_per_member  integer,
  draw_type            text not null default 'lottery',
  conducted            boolean not null default false,
  unique(group_id, cycle_number)
);

create table if not exists public.payments (
  id          text not null default gen_random_uuid()::text,
  cycle_id    text not null references public.cycles(id) on delete cascade,
  member_id   text not null references public.members(id) on delete cascade,
  paid        boolean not null default false,
  paid_date   text,
  mode        text,
  note        text,
  primary key (id),
  unique(cycle_id, member_id)
);

create table if not exists public.member_tokens (
  token      text primary key,
  uid        text not null,
  group_id   text not null references public.groups(id) on delete cascade,
  member_id  text not null references public.members(id) on delete cascade
);

create table if not exists public.fcm_tokens (
  uid        text primary key,
  token      text not null,
  platform   text not null,
  updated_at timestamptz not null default now()
);

-- ─────────────────────────── INDEXES ───────────────────────────────────

create index if not exists groups_uid_idx       on public.groups(uid);
create index if not exists members_group_idx    on public.members(group_id);
create index if not exists cycles_group_idx     on public.cycles(group_id);
create index if not exists payments_cycle_idx   on public.payments(cycle_id);
create index if not exists payments_member_idx  on public.payments(member_id);
create index if not exists mtokens_uid_idx      on public.member_tokens(uid);

-- ─────────────────────────── ROW LEVEL SECURITY ────────────────────────
-- RLS is DISABLED for now (free plan — no Firebase JWT third-party auth yet).
-- When upgrading to Supabase Pro:
--   1. Enable Third-party Auth → Firebase in Dashboard → Authentication
--   2. Re-enable RLS on all tables (uncomment the alter table lines below)
--   3. The policies are already defined and ready to activate.

alter table public.groups        disable row level security;
alter table public.members       disable row level security;
alter table public.cycles        disable row level security;
alter table public.payments      disable row level security;
alter table public.member_tokens disable row level security;
alter table public.fcm_tokens    disable row level security;

-- Policies (inactive until RLS is re-enabled on Pro plan):

create policy "groups_own" on public.groups for all
  using (uid = (auth.jwt() ->> 'sub'))
  with check (uid = (auth.jwt() ->> 'sub'));

create policy "members_via_group" on public.members for all
  using (group_id in (select id from public.groups where uid = (auth.jwt() ->> 'sub')));

create policy "cycles_via_group" on public.cycles for all
  using (group_id in (select id from public.groups where uid = (auth.jwt() ->> 'sub')));

create policy "payments_via_group" on public.payments for all
  using (cycle_id in (
    select c.id from public.cycles c
    join public.groups g on g.id = c.group_id
    where g.uid = (auth.jwt() ->> 'sub')
  ));

create policy "groups_public_via_token" on public.groups for select
  using (id in (select group_id from public.member_tokens));

create policy "member_tokens_public_read"   on public.member_tokens for select using (true);
create policy "member_tokens_foreman_write" on public.member_tokens for insert
  with check (uid = (auth.jwt() ->> 'sub'));

create policy "fcm_own" on public.fcm_tokens for all
  using (uid = (auth.jwt() ->> 'sub'))
  with check (uid = (auth.jwt() ->> 'sub'));
